export const COLUMN = [
    {
        Header:'id',
        accessor:'id'
    },
    {
        Header:'Name',
        accessor:'name'
    },
    {
        Header:'Username',
        accessor:'username'
    },
    {
        Header:'Email',
        accessor:'email'
    },
    {
        Header:'Website',
        accessor:'website'
    },
    {
        Header:'Phone',
        accessor:'phone'
    },
]